### ISSUE TITLE
"init docker" successful but "init include" can't find container

### ISSUE THREAD

**Issue by jasonbert** [eosnewyork/EOSEasyContract#2]
![image](https://user-images.githubusercontent.com/2347572/47797772-e117f080-dd1e-11e8-86d9-e7364afa020a.png)

Firstly, thanks for producing this, EOSIO dev work on Windows is a bit like pushing treacle up a hill at the moment!

I just tried to run through the steps on the README, but hit snag on step 4. Running `init docker` works fine, but then the `init include` isn't able to find the container.

**Comment by WarrickFitz** [comment]
Thanks Jason, that is strange. I'll look into this today and give you an update.

**Comment by jasonbert** [comment]
Looks like the container isn't loaded after downloading the image while Docker is running, I restarted Docker and the container appeared.

![image](https://user-images.githubusercontent.com/2347572/47803241-f3e3f280-dd29-11e8-942f-40038291ec0f.png)

**Comment by WarrickFitz** [comment]
Ah, thanks for the update. I'll investigate and see if I can tell why that happened.

**Comment by yksokolova** [comment]
Hi there, 
I'm Elena
Have the same issue.
I installed docker. When I have in settings for Windows I don't see shared drives option at all. 
Switched in settings for Linux and got the shared option. Chose C and D and got the image downloaded.
So, init docker works, but init include doesn't find an image.
If switch back to windows init docker and init include both don't work.

I did it many times. 
init docker finds an image, init include doesn't find it. (for Linux option in Settings)

So, I guess I should use for Linux (event I'm on Windows 10 pro) and should I completely shut down docker and start it again? Or anything else?


Please suggest.

Thank you, Elena

**Comment by WarrickFitz** [comment]
Thanks, yes, I was able to reproduce the problem. I'm working on a fix at the moment.

**Comment by yksokolova** [comment]
Glad to hear that. And waiting for the solution. Really appreciate the work on windows

**Comment by WarrickFitz** [comment]
My Pleasure, ok, please give this release a go:

https://github.com/eosnewyork/EOSEasyContract/releases/tag/v3.7

@yksokolova note that you should be running docker in Linux mode.

**Comment by yksokolova** [comment]
Hi warrick-eosny,
Everything worked as expected. Thx for fixing it.

I'm on a step 
Uploading your contract to the blockchain

Could you, please help me with that...

On cmd I typed:

c:\tools\EOSEasyContract>docker exec -it EOSCDT-E... /bin/bash

got back:

root@d3dc044d5bb4:/data#

what should i do there?

Please suggest.

Thank you, Elena

**Comment by deckb** [comment]
Hello Elena,

From there you should move to step b https://github.com/eosnewyork/pongpingpong#b-create-wallet-and-import-key

**Comment by jasonbert** [comment]
@warrick-eosny tested and all good now, did the install on a clean machine with Docker freshly installed and running before using the executable.

**Comment by WarrickFitz** [comment]
Great news. Ok, I'm going to close out this issue. Thank you for the feedback and have fun with your contracts. Let us know if you have any other problems.

**Comment by yksokolova** [comment]
Hi Warrick,

I guess i can start with the EOS Smart Contract Tutorial and do all there with the new Contract.
I'd like to keep you posted and thx for the help. My email is : yksokolova@gmail.com or yksokolova@yahoo.com. Can i write to your email instead of writing into closed issues?

Thank you,

Elena
