### ISSUE TITLE
Unknown type 'account_name'

### ISSUE THREAD

**Issue by jasonbert** [eosnewyork/EOSEasyContract#3]
I'm doing some testing with compiling contracts and I'm unable to compile the [EOSIO Hello World](https://developers.eos.io/eosio-cpp/docs/hello-world) contract. It's not able to find the type `account_name`

```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
using namespace eosio;

class hello : public eosio::contract {
	public:
		using contract::contract;

		[[eosio::action]]
		void hi(account_name user) {
			print ("Hello, ", name{user});
		}
}

EOSIO_ABI(hello, (hi))
```

HelloWorld.cpp:10:11: error: unknown type name 'account_name'
                void hi(account_name user) {

Two other compile errors:
HelloWorld.cpp:15:19: error: C++ requires a type specifier for all declarations
EOSIO_ABI(hello, (hi))
HelloWorld.cpp:15:23: error: expected function body after function declarator
EOSIO_ABI(hello, (hi))

**Comment by jasonbert** [comment]
Looks like their documentation is out of date, this isn't an issue with EOSEasyContract. Makes sense why your reference template is different now ;). Seems like the EOS API is still quite in flux.

`EOSIO_ABI` changed to `EOSIO_DISPATCH`, although I haven't found any reference where they've said `account_name` has changed to `name`.

**Comment by WarrickFitz** [comment]
yes, I had some of that confusion myself. This is the best starting point to see ALL the changes: https://eosio.github.io/eosio.cdt/#differences-between-version-12x-and-version-13x

The next thing you'll probably want to move onto is data storage and this is updated to reflect the new syntax it seems: https://developers.eos.io/eosio-home/docs/data-persistence 

Another example: https://github.com/InfiniverseAR/infiniverse-eos/tree/master/infiniverse/src 

I plan to expand the template function so that you can pick from a coupe starter templates in future.

**Comment by jasonbert** [comment]
Cheers, for the links, can be difficult to find EOSIO info :). Do you guys have a chat/channel that's more developer orientated, as opposed to the main EOSNY Telegram.

**Comment by calmesriram** [comment]
Hi Sir,  
     I am new to Eos ( jungle Testnet ). i have tried a small contract which given below. adding two number 
    and result storing in a variable c.after deploying the contract. passing a two argument to contract 
    function.
 1. how do i access the variable c (which is result). if not  is there is any other way to access result.

 #include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>

using namespace eosio;
class add : public contract
{
	public:
        uint64_t c;
	using contract::contract;
	void sum(uint64_t a, uint64_t b)
	{
		c = a + b;
		print("Sum is ",c);
	}
	
	void gdata()
	{
	    print(c);
	}
};

EOSIO_DISPATCH(add, (sum) (gdata))
